#version: "3"
#services:
#  hub:
#    image: selenium/hub:3.141.59
#    ports:
#      - "4444:4444"
#  chrome:
#    image: selenium/node-chrome:3.141.59
#    depends_on:
#      - hub
#    environment:
#      - HUB_HOST=hub
#  firefox:
#    image: selenium/node-firefox:3.141.59
#    depends_on:
#      - hub
#    environment:
#      - HUB_HOST=hub
#  cucumber:
#    image: viacomcbs/aquaweb
#    depends_on:
#     - firefox
#     - chrome
#    environment:
#     - HUB_HOST=hub
#     - BROWSER=chrome
#    volumes:
#     - ./output/result:/viacomcbs/web/test-output



    version: "3"
    services:
      cucumber:
        image: us-docker.pkg.dev/i-cbscom-dev/pplus-qa-automation/cbs-stage-web-smoketest
#        environment:
#          - HUB_HOST=hub
#          - BROWSER=chrome
        volumes:
          - ./output/result:/viacomcbs/web/test-output